# File for Pull Request on main branch
name: PR on main

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          last-successful-event: "release"

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npx nx affected --target=lint

      - name: Tests coverage
        run: npx nx affected --target=test --codeCoverage
