# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Install packages
        run: npm ci

      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          ./.github/scripts/publish-library.sh
