name: Merge on main
on:
  pull_request:
    branches:
      - main
    types: [ closed ]
#  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Code
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/checkout@v2

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Install packages
        run: npm ci

      - name: Publish
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          ./.github/scripts/publish-library.sh
