name: Merge on main
on:
  push:
    branches:
      - main
#  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          last-successful-event: 'release'
          branches: 'main'

      - name: Install packages
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        run: npx semantic-release
